routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', 'login', 301);

Auth::routes(['register' => false]);

Route::group(['middleware' => ['auth']], function() {
    Route::get('home', 'HomeController@index')->name('home');
    Route::get('get-categories', 'HomeController@getCategories')->name('get-categories');
    Route::post('get-sub-categories', 'HomeController@getSubCategories')->name('get-sub-categories');
    Route::get('get-apps', 'HomeController@getApps')->name('get-apps');
    Route::get('get-resource-field-data', 'HomeController@getResourcefieldData')->name('get-resource-field-data');
    Route::post('get-resource-sub-categories', 'HomeController@getResourceSubCategories')->name('get-resource-sub-categories');
    Route::post('create-new', 'HomeController@createNew')->name('create-new');
    
    Route::resource('roles','RoleController')->except(['show']);
    Route::resource('users','UserController')->except(['create', 'show']);
    Route::match(['get', 'post'], 'profile/update', 'UserController@profileUpdate')->name('profile.update');
    Route::resource('apps','AppController');
    Route::resource('chatbots','ChatbotController');
    Route::resource('jurisdictions','JurisdictionController')->except(['create', 'show']);
    Route::resource('resources','ResourceController');
    Route::resource('resource-category','ResourceCategoryController');
    Route::resource('resource-sub-category','ResourceSubCategoryController');
    Route::get('chatbot-request-history', 'ChatbotController@requestHistory')->name('chatbot-request-history');
    Route::get('sender-reports', 'SenderReportController@index')->name('sender-reports');
    Route::get('analytics', 'AnalyticController@index')->name('analytics.index');
});

// Route::view('analytic', 'analytic');

// Route::view('apps', 'apps');

// Route::view('chatbots', 'chatbots');

// Route::view('resetpassword', 'auth/resetpassword');

// Route::view('newpassword', 'auth/newpassword');

// Route::view('managerole', 'managerole');

// Route::view('addrole', 'addrole');

// Route::view('jurisdiction', 'jurisdiction');

resources/views/chatbots.blade.php
@extends('layouts.app')
@section('title', 'Chatbots')
@section('style')
@endsection

@section('content')
<div class="maincontent">
    <div class="titlestrip mb-4">
        <h4>Chatbots</h4>
        <!-- <button type="button"><i class="fas fa-plus"></i> New Chatbot </button> -->
    </div>

    @if (session('success'))
        <div class="alert alert-success" role="alert">
            {{ session('success') }}
        </div>
    @endif

    <div class="app_chatbot_resouces row">
        <div class="col columnstyle app">
        <a href="http://18.222.205.248:5002/login?username=me&password=K0EHyawJbh46" target="_blank">
            <div class="card" style="background: #c6aade;">
                <h4>Health Bot</h4>
            </div>
        </a>
        </div>
        <div class="col columnstyle chatbot">
        <a href="http://13.58.114.5:5002/login?username=me&password=xNxVwU1pcPdo" target="_blank">
            <div class="card" style="background: #57a8ff;">
                <h4>Crime Bot</h4>
            </div>
        </a>
        </div>
        <div class="col columnstyle resouces">
        <a href="http://3.134.253.106:5002/login?username=me&password=Od79UK7XardA" target="_blank">
            <div class="card" style="background: #ff9a9a;">
                <h4>City Bot</h4>
            </div>
        </a>
        </div>
        <div class="col columnstyle resouces">
        <a href="http://52.14.132.240:5002/login?username=me&password=CRp05czYz8qR" target="_blank">
            <div class="card" style="background: #ff9a9a;">
                <h4>School</h4>
            </div>
        </a>
        </div>
    </div>

    <br/>
    <div class="app_chatbot_resouces row">
        <div class="col columnstyle app">
        <a href="http://3.135.236.14:5002/login?username=me&password=cLQaHKy8n7uy" target="_blank">
            <div class="card" style="background: #c6aade;">
                <h4>News</h4>
            </div>
        </a>
        </div>
        <div class="col columnstyle chatbot">
        <a href="http://3.135.223.143:5002/login?username=me&password=axFkiRRqW5b9" target="_blank">
            <div class="card" style="background: #57a8ff;">
                <h4>Products</h4>
            </div>
        </a>
        </div>
        <div class="col columnstyle resouces">
        <a href="http://3.133.122.145:5002/login?username=me&password=k0pIwllCHVKW" target="_blank">
            <div class="card" style="background: #ff9a9a;">
                <h4>General</h4>
            </div>
        </a>
        </div>
    </div>
    
    <br/>
    <div class="mb-4 float-left filters-input">
        <input type="text" name="search-chatbot" id="search-chatbot" placeholder="Search by name" onchange="filter()" value="{{app('request')->input('chatbot')}}">
        <select name="search-status" id="search-status" onchange="filter()">
            <option value="">Select status</option>
            @foreach(Config::get('intelli.chatbot_status') as $csKey => $csVal)
                <option value="{{ $csKey }}" @if(request()->filled('status') && $csKey==app('request')->input('status')) {{ 'selected' }} @endif>{{ $csVal }}</option>
            @endforeach
        <select>
    </div>

    <div class="recentproject_list mt-5 mb-4">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Chatbot Name</th>
                    <th scope="col">Created By</th>
                    <th scope="col">Last Modified</th>
                    <th scope="col">Status</th>
                    <th scope="col" class="text-center">Action</th>
                </tr>
            </thead>
            <tbody>
                @forelse($chatbots as $chatbot)
                <tr>
                    <td>{{ $chatbot->name }}</td>
                    <td>{{ $chatbot->user->name }}</td>
                    <td>
                        @if($chatbot->last_updated_by)
                            {{ \Carbon\Carbon::parse($chatbot->updated_at)->format('d M Y')}}
                        @else
                            {{ \Carbon\Carbon::parse($chatbot->created_at)->format('d M Y')}}
                        @endif
                    </td>
                    <td>
                    @if($chatbot->status == '1')
                        <sapn class="status" style="background:#61d836;"></sapn> {{ 'Active' }} 
                    @elseif($chatbot->status == '2')
                        <sapn class="status" style="background:#1d1d1b;"></sapn> {{ 'Testing' }} 
                    @else 
                        <sapn class="status" style="background:#ed220d;"></sapn> {{ 'Inactive' }} 
                    @endif
                    </td>
                    <td class="text-center">
                        @can('chatbot-edit')
                        <a href="{{ route('chatbots.edit',$chatbot->id) }}" class="chatbot-edit" data-toggle="modal" data-target="#editChatbotData"><i class="fas fa-edit"></i></a>
                        @endcan
                        @can('chatbot-delete')
                        <a href="{{ route('chatbots.destroy',$chatbot->id) }}" class="chatbot-delete"><i class="fas fa-trash-alt"></i></a>
                        @endcan
                    </td>
                </tr>
                @empty
                    <tr><td colspan="6" align="center">No data found</td></tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div>
        {{$chatbots->appends(['chatbot' => app('request')->input('chatbot'), 'status' => app('request')->input('status')])->links()}}
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="editChatbotData" tabindex="-1" role="dialog" aria-labelledby="editChatbotData" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Edit Chatbot</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="alert modal-msg" style="display:none;"></div>
                {!! Form::open(['route'=>['chatbots.update', ''],'method'=>'PUT','id'=>'edit-chatbot-form','files'=>true]) !!}
                <div class="formdesign">
                    <div class="row">
                        <div class="col-md-6 cols float-left">
                            <div class="form-group">
                                <label>App <span style="color:red;">*</span></label>
                                <select name="edit_chatbot_app[]" class="selectpicker multipleselectbox edit_cb_app" multiple data-live-search="true">
                                @foreach($apps as $aKey => $aVal)
                                    <option value="{{ $aKey }}">{{ $aVal }}</option>
                                @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6 cols float-left">
                            <div class="form-group">
                                <label>Name <span style="color:red;">*</span></label>
                                <input type="text" name="edit_chatbot_name" id="edit_chatbot_name" class="form-control">
                            </div>
                        </div>
                        <div class="col-md-6 cols float-left">
                            <div class="form-group">
                                <label>Status <span style="color:red;">*</span></label>
                                <select name="edit_chatbot_status" id="edit_chatbot_status" class="form-control">
                                @foreach(Config::get('intelli.chatbot_status') as $csKey => $csVal)
                                    <option value="{{ $csKey }}" @if($csKey=='1') {{ 'selected' }} @endif>{{ $csVal }}</option>
                                @endforeach
                                <select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="footerbutton text-center p-3 w-100">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </div>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script>
    $(document).ready(function () {

        var cid = null;
        $('.chatbot-edit').on('click',function(e){
            e.preventDefault();
            let url = $(this).attr("href");
            $.ajax({
                url: url,
                type: 'GET',
                success: function (response) {
                    cid = response.chatbot.id;
                    $('select[name="edit_chatbot_app[]"]').val(response.apps);
                    $('.selectpicker').selectpicker('refresh')
                    $('#edit_chatbot_name').val(response.chatbot.name)
                    $('#edit_chatbot_status').val(response.chatbot.status)
                },
                error: function (error) {
                    console.log('Something went wrong, please try again later.')
                },
            });
        });

        $('#edit-chatbot-form').submit(function(e){
            e.preventDefault();
            var formData = new FormData(this);
            let url = $(this).attr('action')+'/'+cid;
            $('.error').remove();
            $.ajax({
                url: url,
                type: 'POST',
                data: formData,
                cache: false,
                contentType: false,
                processData: false,
                success: function (response) {
                    $('.modal-msg').addClass('alert-success');
                    $('.modal-msg').text(response);
                    setTimeout(function () {
                        location.reload();
                    }, 1500);
                    $('.modal-msg').show();
                },
                error: function (error) {
                    let errors = error.responseJSON
                    $.each(errors, function (key, value) {
                        if(key=='edit_chatbot_app') {
                            $(".edit_cb_app:first").after("<small class='error form-text text-danger'>" + value[0] + "</small>")
                        } else {
                            $("input[name='" + key + "'],select[name='"+key+"']").after("<small class='error form-text text-danger'>" + value[0] + "</small>") 
                        }
                    })
                },
            });
        });

        $('.chatbot-delete').on('click', function (e) {
            var url = $(this).attr("href");
            var result = confirm('Are you sure you want to delete the chatbot?'); 
            if (result == true) {
                $.ajax({
                    url: url,
                    type: 'POST',
                    data: {
                        '_method': 'delete',
                        '_token': "{{csrf_token()}}"
                    },
                    success: function (data) {
                        window.location.reload();
                    },
                });
            }
            e.preventDefault()
        });
    });

    function filter() {
        var cht = $('#search-chatbot').val();
        var status = $('#search-status').val();
        var url = APP_URL+"/{{Request::segment(1)}}?chatbot="+cht+"&status="+status;
        if (url) {
            window.location = url;
        }
    }
</script>
@endsection

resources/views/home.blade.php
@extends('layouts.app')
@section('title', 'Dashboard')
@section('style')
@endsection

@section('content')
<div class="maincontent">
    <div class="titlestrip mb-4">
        <h4>Quick Access</h4>
    </div>

    <div class="app_chatbot_resouces row">
        <div class="col columnstyle app">
        <a href="{{ route('apps.index') }}">
            <div class="card" style="background: #c6aade;"><i class="fas fa-tablet-alt"></i>
                <h4>Apps</h4>
            </div>
        </a>
        </div>
        <div class="col columnstyle chatbot">
        <a href="{{ route('chatbots.index') }}">
            <div class="card" style="background: #57a8ff;"><i class="fas fa-comments"></i>
                <h4>Chatbots</h4>
            </div>
        </a>
        </div>
        <div class="col columnstyle resouces">
        <a href="{{ route('resources.index') }}">
            <div class="card" style="background: #ff9a9a;"><i class="fas fa-users"></i>
                <h4>Resources</h4>
            </div>
        </a>
        </div>
    </div>

    <div class="recentproject_list mt-5 mb-4">
        <table class="table">
            <thead>
                <tr>
                    @role('SuperAdmin')
                    <th scope="col">User</th>
                    @endrole
                    <th scope="col">Activity</th>
                    <th scope="col">DateTime</th>
                </tr>
            </thead>
            <tbody>
            @forelse($activities as $activity)
                <tr>
                    @role('SuperAdmin')
                    <td>
                        <div class="thumbnail">
                            @if($activity->user->picture)
                                <span class="img"><img src="{{ url('upload/user-picture') .'/'. $activity->user->picture }}" alt="{{ $activity->user->name }}"></span>
                            @else
                                <span class="img"><img src="{{ url('images/chooseprofile.png') }}" alt="{{ $activity->user->name }}"></span>
                            @endif
                            <p>{{ $activity->user->name }}</p>
                        </div>
                    </td>
                    @endrole
                    <td>{{ $activity->activity }}</td>
                    <td>{{ \Carbon\Carbon::parse($activity->created_at)->format('d M Y h:i A')}}</td>
                </tr>
            @empty
                <tr><td colspan="3" align="center">No data found</td></tr>
            @endforelse
            </tbody>
        </table>
    </div>

    <div>
        {{$activities->links()}}
    </div>
</div>
@endsection

resources/views/jurisdiction.blade.php
@extends('layouts.app')
@section('title', 'Jurisdiction')
@section('style')
@endsection

@section('content')
<div class="maincontent">
    <div class="titlestrip mb-4">
        <h4>Jurisdictions</h4>
        @can('jurisdiction-create')
        <button type="button" class="mapbtn"><i class="fas fa-arrow-down"></i> Add Jurisdiction </button>
        @endcan
    </div>

    @if (session('success'))
        <div class="alert alert-success" role="alert">
            {{ session('success') }}
        </div>
    @endif

    <div class="mb-4  filters-input jurisdictionFilter">
        <input type="text" name="search-jurisdiction" id="search-jurisdiction" placeholder="Search by name" onchange="filter()" value="{{app('request')->input('jurisdiction')}}">
        <select name="search-status" id="search-status" onchange="filter()">
            <option value="">Select status</option>
            @foreach(Config::get('intelli.status') as $csKey => $csVal)
                <option value="{{ $csKey }}" @if(request()->filled('status') && $csKey==app('request')->input('status')) {{ 'selected' }} @endif>{{ $csVal }}</option>
            @endforeach
        <select>
    </div>

    <div class="jurisdictions_map">
        <div id="mapfilter" class="p-3">
            <input id="pac-input" class="controls" type="text" placeholder="Search Here">
            <button type="button" class="btnstyle" id="drawmap" onclick="deleteMarkers();">Reset</button>
        </div>
        <div id="map"></div>
        <div class="formdesign px-3 py-4" style="background: #f7f7f7;box-shadow: inset 0px -1px 0px 1px #e6e6e6;">
            {!! Form::open(['route'=>'jurisdictions.store','method'=>'POST','id'=>'add-jurisdiction-form']) !!}
                <input type="hidden" name="minlatitude" id="minlatitude">
                <input type="hidden" name="maxlatitude" id="maxlatitude">
                <input type="hidden" name="minlongitude" id="minlongitude">
                <input type="hidden" name="maxlongitude" id="maxlongitude">
                <div class="row">
                    <div class="col-md-12">
                        <label><strong>Jurisdiction ID / Jurisdiction Name</strong></label>
                        <div class="form-group">
                            <input type="text" name="nameid" class="form-control" id="jurisdictionname">
                        </div>
                    </div>

                    <div class="col-md-6">
                        <label><strong>Point One</strong></label>
                        <div class="row">
                            <div class="col-md-6 latlngpoints">
                                <div class="form-group">
                                    <label>Latitude</label>
                                    <input type="text" name="pointonelat" class="form-control" id="pointlat_1" readonly>
                                </div>
                            </div>
                            <div class="col-md-6 latlngpoints">
                                <div class="form-group">
                                    <label>Longitude</label>
                                    <input type="text" name="pointonelng" class="form-control" id="pointlng_1" readonly>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <label><strong>Point Two</strong></label>
                        <div class="row">
                            <div class="col-md-6 latlngpoints">
                                <div class="form-group">
                                    <label>Latitude</label>
                                    <input type="text" name="pointtwolat" class="form-control" id="pointlat_2" readonly>
                                </div>
                            </div>
                            <div class="col-md-6 latlngpoints">
                                <div class="form-group">
                                    <label>Longitude</label>
                                    <input type="text" name="pointtwolng" class="form-control" id="pointlng_2" readonly>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <label><strong>Point Three</strong></label>
                        <div class="row">
                            <div class="col-md-6 latlngpoints">
                                <div class="form-group">
                                    <label>Latitude</label>
                                    <input type="text" name="pointthreelat" class="form-control" id="pointlat_3"
                                        readonly>
                                </div>
                            </div>
                            <div class="col-md-6 latlngpoints">
                                <div class="form-group">
                                    <label>Longitude</label>
                                    <input type="text" name="pointthreelng" class="form-control" id="pointlng_3"
                                        readonly>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <label><strong>Point Four</strong></label>
                        <div class="row">
                            <div class="col-md-6 latlngpoints">
                                <div class="form-group">
                                    <label>Latitude</label>
                                    <input type="text" name="pointfourlat" class="form-control" id="pointlat_4"
                                        readonly>
                                </div>
                            </div>
                            <div class="col-md-6 latlngpoints">
                                <div class="form-group">
                                    <label>Longitude</label>
                                    <input type="text" name="pointfourlng" class="form-control" id="pointlng_4"
                                        readonly>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6 text-left">
                        <button type="submit" class="btnstyle">Submit</button>
                    </div>
                </div>
            {!! Form::close() !!}
        </div>
    </div>

    <div class="recentproject_list mt-5 mb-4">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Jurisdiction</th>
                    <th scope="col">Created By</th>
                    <th scope="col">Last Modified</th>
                    <th scope="col">Status</th>
                    <th scope="col" class="text-center">Action</th>
                </tr>
            </thead>
            <tbody>
                @forelse($jurisdictions as $jurisdiction)
                <tr>
                    <td>{{ $jurisdiction->name }}</td>
                    <td>{{ $jurisdiction->user->name }}</td>
                    <td>
                        @if($jurisdiction->last_updated_by)
                            {{ \Carbon\Carbon::parse($jurisdiction->updated_at)->format('d M Y')}}
                        @else
                            {{ \Carbon\Carbon::parse($jurisdiction->created_at)->format('d M Y')}}
                        @endif
                    </td>
                    <td>
                    @if($jurisdiction->status == '1')
                        <sapn class="status" style="background:#61d836;"></sapn> {{ 'Active' }} 
                    @else 
                        <sapn class="status" style="background:#ed220d;"></sapn> {{ 'Inactive' }} 
                    @endif
                    </td>
                    <td class="text-center">
                        @can('jurisdiction-edit')
                        <a href="{{ route('jurisdictions.edit', $jurisdiction->id) }}" class="jurisdiction-edit"><i class="fas fa-edit"></i></a>
                        @endcan
                        @can('jurisdiction-delete')
                        <a href="{{ route('jurisdictions.destroy',$jurisdiction->id) }}" class="jurisdiction-delete"><i class="fas fa-trash-alt"></i></a>
                        @endcan
                    </td>
                </tr>
                @empty
                    <tr><td colspan="6" align="center">No data found</td></tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div>
        {{$jurisdictions->appends(['jurisdiction' => app('request')->input('jurisdiction'), 'status' => app('request')->input('status')])->links()}}
    </div>
</div>
@endsection

@section('script')
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAI2X826A0AJ5dGzXkeQQDRkzJV5-5JHE4&libraries=places&callback=initMap"></script>
<script src="{{ asset('js/main/jurisdiction.map.js') }}"></script>
<script>
    $(document).ready(function () {

        $('#add-jurisdiction-form').submit(function(e){
            e.preventDefault();
            var formData = $('#add-jurisdiction-form').serialize();
            let url = $(this).attr('action');
            let method = $(this).attr('method');
            $('.error').remove()
            
            $.ajax({
                url: url,
                type: method,
                data: formData,
                success: function (response) {
                    setTimeout(function () {
                        location.reload();
                    }, 1000);
                },
                error: function (error) {
                    let errors = error.responseJSON
                    $.each(errors, function (key, value) {
                        $("input[name='" + key + "']").after("<small class='error form-text text-danger'>" + value[0] + "</small>")                      
                    })
                },
            });
        });

        $('.jurisdiction-delete').on('click', function (e) {
            var url = $(this).attr("href");
            var result = confirm('Are you sure you want to delete the jurisdiction?'); 
            if (result == true) {
                $.ajax({
                    url: url,
                    type: 'POST',
                    data: {
                        '_method': 'delete',
                        '_token': "{{csrf_token()}}"
                    },
                    success: function (data) {
                        window.location.reload();
                    },
                });
            }
            e.preventDefault()
        });

    }); // Ready Close Here

    function filter() {
        var jur = $('#search-jurisdiction').val();
        var status = $('#search-status').val();
        var url = APP_URL+"/{{Request::segment(1)}}?jurisdiction="+jur+"&status="+status;
        if (url) {
            window.location = url;
        }
    }
</script>
@endsection