routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', 'login', 301);

Auth::routes(['register' => false]);

Route::group(['middleware' => ['auth']], function() {
    Route::get('home', 'HomeController@index')->name('home');
    Route::get('get-categories', 'HomeController@getCategories')->name('get-categories');
    Route::post('get-sub-categories', 'HomeController@getSubCategories')->name('get-sub-categories');
    Route::get('get-apps', 'HomeController@getApps')->name('get-apps');
    Route::get('get-resource-field-data', 'HomeController@getResourcefieldData')->name('get-resource-field-data');
    Route::post('get-resource-sub-categories', 'HomeController@getResourceSubCategories')->name('get-resource-sub-categories');
    Route::post('create-new', 'HomeController@createNew')->name('create-new');
    
    Route::resource('roles','RoleController')->except(['show']);
    Route::resource('users','UserController')->except(['create', 'show']);
    Route::match(['get', 'post'], 'profile/update', 'UserController@profileUpdate')->name('profile.update');
    Route::resource('apps','AppController');
    Route::resource('chatbots','ChatbotController');
    Route::resource('jurisdictions','JurisdictionController')->except(['create', 'show']);
    Route::resource('resources','ResourceController');
    Route::resource('resource-category','ResourceCategoryController');
    Route::resource('resource-sub-category','ResourceSubCategoryController');
    Route::get('chatbot-request-history', 'ChatbotController@requestHistory')->name('chatbot-request-history');
    Route::get('sender-reports', 'SenderReportController@index')->name('sender-reports');
    Route::get('analytics', 'AnalyticController@index')->name('analytics.index');
});

// Route::view('analytic', 'analytic');

// Route::view('apps', 'apps');

// Route::view('chatbots', 'chatbots');

// Route::view('resetpassword', 'auth/resetpassword');

// Route::view('newpassword', 'auth/newpassword');

// Route::view('managerole', 'managerole');

// Route::view('addrole', 'addrole');

// Route::view('jurisdiction', 'jurisdiction');

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use DB;
use Request as Req;
use App\Activity;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('permission:role-list');
        $this->middleware('permission:role-create', ['only' => ['create','store']]);
        $this->middleware('permission:role-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:role-delete', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $roles = Role::paginate(10);

        //Save activity
        $activity = new Activity();
        $activity->activity = 'Visited role list page.';
        $activity->user_id = \Auth::user()->id;
        $activity->save();

        return view('roles.index', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions = Permission::get()->groupBy('module');
        return view('roles.create',compact('permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:roles,name',
            'permission' => 'required',
        ]);

        $role = Role::create(['name' => $request->input('name')]);
        $role->syncPermissions($request->input('permission'));

        //Save activity
        $activity = new Activity();
        $activity->activity = 'Created new role.';
        $activity->user_id = \Auth::user()->id;
        $activity->save();

        return redirect()->route('roles.index')->with('success','Role created successfully.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        $permissions = Permission::get()->groupBy('module');
        $rolePermissions = DB::table("role_has_permissions")->where("role_has_permissions.role_id",$role->id)
            ->pluck('role_has_permissions.permission_id','role_has_permissions.permission_id')
            ->all();

        return view('roles.edit',compact('role','permissions','rolePermissions'));
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Role $role)
    {
        $this->validate($request, [
            'name' => 'required|unique:roles,name,'.$role->id,
            'permission' => 'required',
        ]);

        $role->name = $request->input('name');
        $role->save();

        $role->syncPermissions($request->input('permission'));

        //Save activity
        $activity = new Activity();
        $activity->activity = 'Updated role details.';
        $activity->user_id = \Auth::user()->id;
        $activity->save();

        return redirect()->route('roles.index')->with('success','Role updated successfully');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        $role->delete();

        //Save activity
        $activity = new Activity();
        $activity->activity = 'Deleted role.';
        $activity->user_id = \Auth::user()->id;
        $activity->save();

        Req::session()->flash('success', 'Role deleted successfully.');
        return response()->json('Role deleted successfully.', 200);
    }
}

resources/views/roles/create.blade.php
@extends('layouts.app')
@section('title', 'Roles')
@section('style')
@endsection

@section('content')
<div class="maincontent">
    <div class="titlestrip mb-4">
        <h4>Add Role</h4>
    </div>

    <!-- <div class="breadcrumb-parent">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">Add Role</li>
            </ol>
        </nav>
    </div> -->

    <div class="recentproject_list mt-5 mb-4">
        <div class="addrolecontent formdesign ">
            {!! Form::open(array('route' => 'roles.store','method'=>'POST')) !!}
            <div class="col-md-4">
                <div class="form-group">
                    <lable>Name <span style="color:red;">*</span></lable>
                    {!! Form::text('name', null, array('placeholder' => 'Role Name','class' => 'form-control','id' => "role_name", 'maxlength'=>'125' )) !!}
                    @error('name')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>
            </div>
            <div class="col-md-12 mt-4">
                <h3>Permission <span style="color:red;">*</span></h3>
                @error('permission')
                <small class="form-text text-danger font-weight-500">{{ $message }}</small>
                @enderror
                <ul class="permission_list mt-4">
                    @foreach($permissions as $key=>$perms)
                    <li>
                        <label class="container_checkbox">
                            <input type="checkbox" class="module" data-id="{{ str_replace(' ', '-', strtolower($key)) }}">
                            <span class="checkmark"></span>
                        </label>
                        <div class="content">{{$key}} <i class="fas fa-chevron-down"></i></div>
                        <div class="first_level_dropdown">
                            <ul class="sublevellist">
                                @foreach($perms as $perm)
                                <li>
                                    <label class="container_checkbox">
                                        {{ Form::checkbox('permission[]', $perm->id, false, array('class' => 'name permission', 'data-module' => str_replace(' ', '-', strtolower($key)))) }} {{ $perm->action }}
                                        <span class="checkmark"></span>
                                    </label>
                                </li>
                                @endforeach
                            </ul>
                        </div>
                    </li>
                    @endforeach
                </ul>
            </div>

            <div class="col-md-12 mt-4">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>
@endsection

@section('script')
<script>
    $(document).ready(function () {
        $('.permission_list li .content').on('click', function () {
            $(this).parents('li').find('.first_level_dropdown').slideToggle();
        });

        $('.module').on('click',function() {
            var module = $(this).attr("data-id");
            $('input[type="checkbox"][data-module="'+module+'"]').prop('checked', $(this).prop("checked"));
        });

        $('.permission').on('click',function() {
            var module = $(this).attr("data-module");
            if($(this).prop("checked")) {
                if($('input[type="checkbox"][data-module="'+module+'"]').length === $('input[type="checkbox"][data-module="'+module+'"]').filter(":checked").length) {
                    $('input[type="checkbox"][data-id="'+module+'"]').prop('checked', true);
                }
            } else {
                $('input[type="checkbox"][data-id="'+module+'"]').prop('checked', false);
            }
        });
    });
</script>
@endsection

resources/views/roles/edit.blade.php
@extends('layouts.app')
@section('title', 'Roles')
@section('style')
@endsection

@section('content')
<div class="maincontent">
    <div class="titlestrip mb-4">
        <h4>Edit Role</h4>
    </div>

    <!-- <div class="breadcrumb-parent">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">Add Role</li>
            </ol>
        </nav>
    </div> -->

    <div class="recentproject_list mt-5 mb-4">
        <div class="addrolecontent formdesign ">
            {!! Form::model($role, ['method' => 'PATCH','route' => ['roles.update', $role->id]]) !!}
            <div class="col-md-4">
                <div class="form-group">
                    <lable>Name <span style="color:red;">*</span></lable>
                    {!! Form::text('name', null, array('placeholder' => 'Role Name','class' => 'form-control','id' => "role_name", 'maxlength'=>'125' )) !!}
                    @error('name')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>
            </div>
            <div class="col-md-12 mt-4">
                <h3>Permission <span style="color:red;">*</span></h3>
                @error('permission')
                <small class="form-text text-danger font-weight-500">{{ $message }}</small>
                @enderror
                <ul class="permission_list mt-4">
                    @foreach($permissions as $key=>$perms)
                    <li>
                        <label class="container_checkbox">
                            <input type="checkbox" class="module" data-id="{{ str_replace(' ', '-', strtolower($key)) }}">
                            <span class="checkmark"></span>
                        </label>
                        <div class="content">{{$key}} <i class="fas fa-chevron-down"></i></div>
                        <div class="first_level_dropdown">
                            <ul class="sublevellist">
                                @foreach($perms as $perm)
                                <li>
                                    <label class="container_checkbox">
                                        {{ Form::checkbox('permission[]', $perm->id, in_array($perm->id, $rolePermissions) ? true : false, array('class' => 'name permission', 'data-module' => str_replace(' ', '-', strtolower($key)))) }} {{ $perm->action }}
                                        <span class="checkmark"></span>
                                    </label>
                                </li>
                                @endforeach
                            </ul>
                        </div>
                    </li>
                    @endforeach
                </ul>
            </div>

            <div class="col-md-12 mt-4">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>
@endsection

@section('script')
<script>
    $(document).ready(function () {
        $('.permission_list li .content').on('click', function () {
            $(this).parents('li').find('.first_level_dropdown').slideToggle();
        });

        $('.module').on('click',function() {
            var module = $(this).attr("data-id");
            $('input[type="checkbox"][data-module="'+module+'"]').prop('checked', $(this).prop("checked"));
        });

        $('.permission').on('click',function() {
            var module = $(this).attr("data-module");
            if($(this).prop("checked")) {
                if($('input[type="checkbox"][data-module="'+module+'"]').length === $('input[type="checkbox"][data-module="'+module+'"]').filter(":checked").length) {
                    $('input[type="checkbox"][data-id="'+module+'"]').prop('checked', true);
                }
            } else {
                $('input[type="checkbox"][data-id="'+module+'"]').prop('checked', false);
            }
        });

        $('.module').each(function () {
            var parent = $(this).attr("data-id");
            if($('input[type="checkbox"][data-module="'+parent+'"]').length === $('input[type="checkbox"][data-module="'+parent+'"]').filter(":checked").length) {
                $(this).prop('checked', true);
            }
        });
    });
</script>
@endsection

resources/views/roles/index.blade.php
@extends('layouts.app')
@section('title', 'Roles')
@section('style')
@endsection

@section('content')
<div class="maincontent">
    <div class="titlestrip mb-4">
        <h4>Roles</h4>
        @can('role-create')
        <a class="titlebtn" href="{{route('roles.create')}}"><i class="fas fa-plus"></i> Add Role </a>
        @endcan
    </div>

    @if (session('success'))
        <div class="alert alert-success" role="alert">
            {{ session('success') }}
        </div>
    @endif

    <div class="recentproject_list mt-5 mb-4">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col" width="100">Sr. No.</th>
                    <th scope="col">Role Name</th>
                    <th scope="col" class="text-center" width="200">Action</th>
                </tr>
            </thead>
            <tbody>
            @forelse($roles as $role)
                <tr>
                    <td>{{(($roles->currentpage()-1)*$roles->perPage()) + $loop->index+1 }}</td>
                    <td>{{$role->name}}</td>
                    <td class="text-center">
                        @can('role-edit')
                        <a href="{{ route('roles.edit',$role->id) }}"><i class="fas fa-edit"></i></a>
                        @endcan
                        @can('role-delete')
                        <a href="{{ route('roles.destroy',$role->id) }}" class="role-delete"><i class="fas fa-trash-alt"></i></a>
                        @endcan
                    </td>
                </tr>
            @empty
                <tr><td colspan="3" align="center">No data found</td></tr>
            @endforelse
            </tbody>
        </table>
    </div>

    <div>
        {{$roles->links()}}
    </div>
</div>
@endsection

@section('script')
<script>
    $(document).ready(function () {
        $('.role-delete').on('click', function (e) {
            var url = $(this).attr("href");
            var result = confirm('Are you sure you want to delete the role?'); 
            if (result == true) {
                $.ajax({
                    url: url,
                    type: 'POST',
                    data: {
                        '_method': 'delete',
                        '_token': "{{csrf_token()}}"
                    },
                    success: function (data) {
                        window.location.reload();
                    },
                });
            }
            e.preventDefault()
        });
    });
</script>
@endsection